common:
  prefix: "Taupede_ftp"
  xscale: "linear"
  yscale: "log"
  ylabel: "Rate per year"
  legend_loc: "best"
  weights_map: "weight"
  normalized: false
  #histtype: "step"
  #save_path: "output/histogram.png" 
  show: true
  hist_weight: "weight_13years"
  errorbar_weight: "weight_1"
  colors: ['b','y','g','r']
  ylabel_ratio: "Data/MC Ratio"
  ylim_ratio: [0,2]


plot_type: stacked_hist_with_ratio

variables:
  MonopodE:
    column: "cscdSBU_MonopodFit4_noDC_energy"            # Data column to plot
    bins:
      function: logspace
      start: 4.5
      stop: 7
      num: 20
    xlabel: "Energy[GeV]"
    title: "Monopod Energy"
    xscale: "log"
    
  TaupedeAsymmetry:
    column: "{prefix}_Asymmetry_value"
    bins:
      function: linspace
      start: -1
      stop: 1
      num: 20
    xlabel: "Asymmetry"
    title: "Taupede Asymmetry"
    legend_loc: "lower right"
    
  Taupede1Energy:
    column: "{prefix}_1Particles_energy"
    bins:
      function: logspace
      start: 2
      stop: 7
      num: 20
    xlabel: "Energy[GeV]"
    title: "Taupede 1st Cascade Energy"
    xscale: "log"


  Taupede2Energy:
    column: "{prefix}_2Particles_energy"
    bins:
      function: logspace
      start: 2
      stop: 7
      num: 20
    xlabel: "Energy[GeV]"
    title: "Taupede 2nd Cascade Energy"
    xscale: "log"

  TaupedeDistance:
    column: "{prefix}_Distance_value"
    bins:
      function: linspace
      start: 0
      stop: 100
      num: 20
    xlabel: "Length[m]"
    title: "Taupede Cascade Distance"

  Taupede_ftpFitParams_rlogl:
    column: "{prefix}FitParams_rlogl"
    bins:
      function: linspace
      start: 4.5
      stop: 9
      num: 20
    xlabel: "rlogl"
    title: "Taupede rlogl"
    
  cscdSBU_MonopodFit4_noDCFitParams_rlogl:
    column: "cscdSBU_MonopodFit4_noDCFitParams_rlogl"
    bins:
      function: linspace
      start: 4.5
      stop: 9
      num: 20
    xlabel: "rlogl"
    title: "Monopod rlogl"
    
  TauMonorlogldiff:
    column: "{prefix}MonoDiff_rlogl_value"
    bins:
      function: linspace
      start: -0.5
      stop: 0.1
      num: 20
    xlabel: "Difference"
    title: "Taupede Monopod rlogl difference"
    
  Taupede_ftpFitParams_logl:
    column: "{prefix}FitParams_logl"
    bins:
      function: logspace
      start: 2.5
      stop: 6
      num: 20
    xlabel: "logl"
    title: "Taupede logl" 
    xscale: "log"

  
  cscdSBU_MonopodFit4_noDCFitParams_logl:
    column: "cscdSBU_MonopodFit4_noDCFitParams_logl"
    bins:
      function: logspace
      start: 2.5
      stop: 6
      num: 20
    xlabel: "logl"
    title: "Monopod logl"  
    xscale: "log"
    
    
  Taupede_ftpFitParams_ndof:
    column: "{prefix}FitParams_ndof"
    bins:
      function: linspace
      start: 0
      stop: 10000
      num: 30
    xlabel: "ndof"
    title: "Taupede ndof"
    
  cscdSBU_MonopodFit4_noDCFitParams_ndof:
    column: "cscdSBU_MonopodFit4_noDCFitParams_ndof"
    bins:
      function: linspace
      start: 0
      stop: 10000
      num: 30
    xlabel: "ndof"
    title: "Monopod ndof"
    
    
  Totalcharge:
    column: "cscdSBU_LE_bdt_input_cscdSBU_Qtot_HLC_log_value"
    bins:
      function: linspace
      start: 3
      stop: 6
      num: 20
    xlabel: "Charge"
    title: "Total Charge"
     
    
  cscdSBU_I3XYScale_noDC_value:
    column: "cscdSBU_LE_bdt_input_cscdSBU_I3XYScale_noDC_value"
    bins:
      function: linspace
      start: 0
      stop: 1
      num: 20
    xlabel: "XY scale"
    title: "cscdSBU_I3XYScale_noDC_value"  

    
  cscdSBU_MonopodFit4_noDC_Delay_ice_value:
    column: "cscdSBU_LE_bdt_input_cscdSBU_MonopodFit4_noDC_Delay_ice_value"
    bins:
      function: linspace
      start: -200
      stop: 100
      num: 20
    xlabel: "Delay_ice_value"
    title: "cscdSBU_MonopodFit4_noDC_Delay_ice_value"  


  cscdSBU_MonopodFit4_noDC_zenith:
    column: "cscdSBU_LE_bdt_input_cscdSBU_MonopodFit4_noDC_zenith"
    bins:
      function: linspace
      start: 0
      stop: 3.15
      num: 20
    xlabel: "zenith"
    title: "cscdSBU_MonopodFit4_noDC_zenith" 

  cscdSBU_VertexRecoDist_CscdLLh:
    column: "cscdSBU_LE_bdt_input_cscdSBU_VertexRecoDist_CscdLLh"
    bins:
      function: linspace
      start: 0
      stop: 25
      num: 20
    xlabel: "RecoDist"
    title: "cscdSBU_VertexRecoDist_CscdLLh" 


  q_max_doms:
    column: "CVStatistics_q_max_doms"
    bins:
      function: logspace
      start: 1.5
      stop: 5
      num: 20
    xlabel: "CVStatistics_q_max_doms"
    title: "q_max_doms" 
    xscale: "log"

  cscdSBU_MonopodFit4_noDC_z:
    column: "cscdSBU_MonopodFit4_noDC_z"
    bins:
      function: linspace
      start: -500
      stop: 500
      num: 20
    xlabel: "z"
    title: "cscdSBU_MonopodFit4_noDC_z"  


  cscdSBU_MonopodFit4_noDC_x:
    column: "cscdSBU_MonopodFit4_noDC_x"
    bins:
      function: linspace
      start: -500
      stop: 500
      num: 20
    xlabel: "x"
    title: "cscdSBU_MonopodFit4_noDC_x"  
    
    
  cscdSBU_MonopodFit4_noDC_y:
    column: "cscdSBU_MonopodFit4_noDC_y"
    bins:
      function: linspace
      start: -500
      stop: 500
      num: 20
    xlabel: "y"
    title: "cscdSBU_MonopodFit4_noDC_y"  
